version: '2'
services:
    gdpr-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/gdpr/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=gdpr
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
